# Generated by Django 5.0.6 on 2024-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=15)),
                ('NationCode', models.CharField(max_length=15)),
                ('password', models.CharField(default=12345678, max_length=50)),
                ('address', models.CharField(default='iran', max_length=100)),
                ('LandlineNumber', models.CharField(default='011', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
