# Generated by Django 5.0.6 on 2024-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blockStatus',
            field=models.BooleanField(default=False),
        ),
    ]
