# Generated by Django 5.0.6 on 2024-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_person_blockstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='LandlineNumber',
            field=models.CharField(blank=True, default='011', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='Mobile',
            field=models.CharField(blank=True, default='09', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default='iran', max_length=100),
        ),
    ]
