# Generated by Django 5.0.6 on 2024-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='Nation_pictures/'),
        ),
    ]
