# Generated by Django 5.0.6 on 2024-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_person_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='public/media/Nation_pictures/'),
        ),
    ]
