# Generated by Django 5.0.6 on 2024-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_person_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='Nation_pictures/'),
        ),
    ]
