# Generated by Django 5.0.6 on 2024-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_person_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blockStatus',
            field=models.BooleanField(default=True),
        ),
    ]
