# Generated by Django 5.0.6 on 2024-11-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_person_blockstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='new_customer_status',
            field=models.BooleanField(default=False),
        ),
    ]
