# Generated by Django 5.0.6 on 2024-07-08 07:55

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='BuyRequst',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.invoice')),
                ('number', models.CharField(max_length=16, unique=True)),
            ],
            bases=('payment.invoice',),
        ),
        migrations.CreateModel(
            name='convertGoldRequst',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.invoice')),
                ('gold', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
            bases=('payment.invoice',),
        ),
        migrations.CreateModel(
            name='sellRequst',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.invoice')),
                ('image', models.ImageField(upload_to='media/sell/')),
            ],
            bases=('payment.invoice',),
        ),
        migrations.CreateModel(
            name='paymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('inventory', models.DecimalField(decimal_places=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
