# Generated by Django 5.0.6 on 2024-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='inventory',
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='endurance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='goldInventory',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='moneyInventory',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
