# Generated by Django 5.0.6 on 2024-07-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_user_alter_paymentaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='endurance',
        ),
    ]
