# Generated by Django 5.0.6 on 2024-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_buyrequst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
