# Generated by Django 5.0.6 on 2024-07-19 14:51

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
