# Generated by Django 5.0.6 on 2024-07-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='nameCart',
        ),
    ]
