# Generated by Django 5.0.6 on 2024-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_paymentaccount_namecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='nameCart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
