# Generated by Django 5.0.6 on 2024-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequst',
            name='nameCart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
