# Generated by Django 5.0.6 on 2024-07-27 17:22

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_buyrequst_namecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sellrequst',
            name='image',
            field=models.ImageField(upload_to='public/media/sell/'),
        ),
    ]
