# Generated by Django 5.0.6 on 2024-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_invoice_date_alter_paymentaccount_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequst',
            name='number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
