# Generated by Django 5.0.6 on 2024-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_alter_convertgoldrequst_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequst',
            name='image',
            field=models.ImageField(upload_to='sell/'),
        ),
    ]
