# Generated by Django 5.0.6 on 2024-08-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_alter_sellrequst_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='sheba',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
