# Generated by Django 5.0.6 on 2024-08-19 14:03

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_paymentaccount_sheba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequst',
            name='nameCart',
        ),
        migrations.RemoveField(
            model_name='buyrequst',
            name='number',
        ),
        migrations.AddField(
            model_name='paymentdate',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdate',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
