# Generated by Django 5.0.6 on 2024-08-19 14:06

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_remove_buyrequst_namecart_remove_buyrequst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdate',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
