# Generated by Django 5.0.6 on 2024-08-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_convertmoneyrequst_getgoldrequst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertgoldrequst',
            name='gold',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='convertmoneyrequst',
            name='gold',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='getgoldrequst',
            name='gold',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
