# Generated by Django 5.0.6 on 2024-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_alter_convertgoldrequst_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertgoldrequst',
            name='gold',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
