# Generated by Django 5.0.6 on 2024-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_alter_convertmoneyrequst_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='goldInventory',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
